#!/bin/sh -x
#
# restauration du clavier
#
# Copyright (C) 2008 Gaëtan Lehmann <gaetan.lehmann@jouy.inra.fr>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#

set -ev

# quel répertoire temporaire utiliser ?
if [ -n "$TMP" ]; then
  tmp="$TMP"
elif [ -n "$TMPDIR" ]; then
  tmp="$TMPDIR"
else
  tmp=/tmp
fi
dump="$tmp/$USER-dump.xkb"

if [ -e "$dump" ]; then
  xkbcomp -w0 "$dump" $DISPLAY
else
  # pas de fichier - on repasse en azerty
  setxkbmap fr
fi
